### PR TITLE
replaced deprecated gulp-util and fixed broken test

### PR DESCRIPTION
**Pull request by zbennett10**
This pr replaces the recently deprecated gulp-util package with corresponding dependencies.

For more info see:

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
gulpjs/gulp-util#143

Thanks!

### CODE REVIEW

**Comment by demurgos** [comment]
Looks like we sent our PRs almost at the same time. I am still waiting for CI but did not apply your fix for the tests so it may fail: in this case it may be better to keep your PR.

See:
#128

**Comment by zbennett10** [comment]
Yeah - one right after the other, haha! 

I see that your tests have passed regardless of the "fix" that i added. The test I tried fix may have been failing on my machine because I am using Windows. At any rate, it's probably best just to keep your PR since it focuses on the task at hand.

**Comment by demurgos** [comment]
@SBoudrias 
Could you merge and publish one of the PRs?

**Comment by SBoudrias** [comment]
Thanks! I'll publish once back from vacation

**Pull request merged**
