### PR TITLE
ES6 Loaders - Added new skipImports

### PR DESCRIPTION
**Pull request by markwylde**
### The Issue
There is currently no way to ignore certain imports from occurring. For example, if you are using ES6 and the `isparta.Instrumenter` then you might have a `.js` file that looks like this
```javascript
import 'RandomFile.js';
import 'RandomFile2.js';

import 'MyStyle.scss'; // <<<<< This is the culprit 

let myApplication = () => {
    ...
```

The `.js` files will (as expected) import without any problem using the `isparta` plugin, however when it comes to the `MyStyle.scss` file, it will fail. During compilation, Webpack allows `module loaders` which in turn will add this to the `bundle.js` file, so the `module loader` will understand the `.scss` file needs to be transpiled and added to the bundle. However, we don't have this luxery when it comes to `istanbul` and therefore need a solution to solving the errors these imports bring.

### The Solution
The solution in my pull request adds an extra option to `gulp-istanbul` called `skipImports`. This must be a regex that contains a matcher of files to ignore.

You can supply the `skipImports` option directly to the `gulp-istanbul` call as below:
```javascript
istanbul({
  // skip both scss and css files
  skipImports: /\.s{0,1}css$/
})
```

Or a more verbose way of writing it:
```javascript
istanbul({
  skipImports: /\.(scss|css)$/
})
```

As a result, your `gulpfile.js` may now look something like this:
```javascript
gulp.task('unit_tests', function(cb) {
  gulp.src(['src/**/*.js'])
    .pipe(istanbul({
      instrumenter: Instrumenter,
      includeUntested: true,
      skipImports: /\.s{0,1}css$/
    }))
    .pipe(istanbul.hookRequire())
    .on('finish', function() {
      gulp.src(['src/**/*.spec.js'])
        .pipe(mocha())
        .pipe(istanbul.writeReports())
        .pipe(istanbul.enforceThresholds({ thresholds: { global: 90 } }))
        .on('end', cb);
    });
});
```

### The In's and Out's
Istanbul has a `hookRequire` method which `gulp-istanbul` is already using to (I believe) cache and load covered files. For this adjustment I changed the code of `gulp-istanbul/index.js` file to include a `skipMatcher` method after globally exposing the `skipImports` option.

The method looks like this:
```javascript
var skipMatcher = function (file) {
  if (skipImports) {
    return file.match(skipImports) ? true : false;
  } else {
    return false;
  }
};
```

It takes a file, and returns whether it matches the skipImports regex specified in the gulpfile.

Now that we have this method, I needed to include it in the `hookRequire`. This was easy enough and just means we need to add our new `skipMatcher` method into the existing `gulp-istanbul` code, which in the end looks like:
```javascript
istanbul.hook.hookRequire(function (path) {
  return !!fileMap[path] || skipMatcher(path);
}, function (code, path) {
  if (skipMatcher(path)) {
    //console.log('File skipped: ' + path);
    return '';
  } else {
    return fileMap[path];
  }
}, options);
```

### Conclusion
I think for a more long term solution it would be great if the core `istanbul` team could add an option to allow webpack loaders to be specified and used, but until that time I think this is an adequate work around. I'm sure it will also have use for some people who are just using ES5 but want to ignore certain files from their coverage.

#### Future Work
In the future if other people need it (or myself), then it might be nice if instead of just ignoring the file you could pass a function to the `skipImports` option which would then run for each file. Currently I just don't have the use case for this, but I think it would be very easy to modify this to get the desired result.

p.s. Thanks SBoudrias for your energy and time on this project. You're a hero and have saved weeks off my time!

### CODE REVIEW

**Comment by SBoudrias** [comment]
I feel like you might not be targeting the correct tool. If isparta is having an issue with imports who're not JS, you should send them a PR...

Gulp-istanbul really just is a wrapper over istanbul. I don't feel we should merge fix for stuff Istanbul or isparta could fix.

**Comment by markwylde** [comment]
Yeah @SBoudrias I do agree with you, however as part of the core `istanbul` package there is the following ignoring features that we're not implementing in this wrapper:
***See [Ignoring Code for Coverage](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md)***

There is also the ability (in isparta (I believe)[https://github.com/douglasduteil/isparta]) to add in babel configuration options which we're not doing. For example:
```javascript
{
  // configure the reporter to use isparta for JavaScript coverage
  // Only on { "karma-coverage": "douglasduteil/karma-coverage#next" }
  instrumenters: { isparta : require('isparta') },
  instrumenter: {
    '**/*.js': 'isparta'
  },
  instrumenterOptions: {
    isparta: { babel : babelMoreOptions }
  }
}
```

But to be honest I myself don't have a clue how I would start to implement this. Plus `isparta` was made mainly for karma and not necessary gulp, so we do have different scope than that project.

But I do think you raise a valid point. Istanbul should maybe offer this type of functionality. Maybe it's worth posting this issue over there and I'll see what the response is like.

Regardless, as more people start using React with ES6/Webpack I can see this being a feature a few people need. A little confused at this point...

**Comment by markwylde** [comment]
Looking a bit deeper into this there is an `[ignore](https://babeljs.io/docs/usage/options/)` option in babel.

If there was a way to pass options to the `instrumenter` we could end up with a babel file that looks like:
```javascript
gulp.task('unit_tests', function(cb) {
  gulp.src(['src/**/*.js'])
    .pipe(istanbul({
      instrumenter: Instrumenter,
      instrumenterOptions: {
        babel: {
          ignore: /\.(scss|css)$/
        }
      }
      includeUntested: true,
      skipImports: /\.s{0,1}css$/
    }))
    .pipe(istanbul.hookRequire())
    .on('finish', function() {
      gulp.src(['src/**/*.spec.js'])
        .pipe(mocha())
        .pipe(istanbul.writeReports())
        .pipe(istanbul.enforceThresholds({ thresholds: { global: 90 } }))
        .on('end', cb);
    });
});
```

Can you think of a way we could easily expose these options?

**Comment by SBoudrias** [comment]
Let's keep it open until we figure out a solution.

**Comment by SBoudrias** [comment]
Ok so, FWIW, the options passed to `gulp-istanbul`(`instabul(options)`) are also passed directly to the instrumenter. https://github.com/SBoudrias/gulp-istanbul/blob/master/index.js#L24

This should be good enough to pass babel options.

**Pull request closed without merging**
